// <auto-generated />
namespace DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class shopChangeReq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shopChangeReq));
        
        string IMigrationMetadata.Id
        {
            get { return "202204120450406_shopChangeReq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
