// <auto-generated />
namespace DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class sellerDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sellerDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202204120518141_sellerDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
